name: hookezy
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+2

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  dio: ^4.0.0
  shared_preferences: 2.0.5
  flushbar: ^1.10.4
  razorpay_flutter: ^1.2.5
  toast: ^0.1.5
  device_info: ^0.4.0+4
  cached_network_image: ^3.0.0

  stripe_payment: ^1.1.4
  http: ^0.13.1
  image_picker: ^0.7.4
  flutter_spinkit: ^4.1.2
  permission_handler: ^6.1.1
  agora_rtc_engine: ^3.2.1
  secure_application: ^3.5.3
  stories_for_flutter: ^0.1.8
  rxdart: ^0.26.0
  flutter_cache_manager: ^3.0.1
  story_view: ^0.13.0-nullsafety.1
  carousel_slider: ^1.3.0
  firebase_core: ^1.0.3
  firebase_messaging: ^9.1.1
  route_observer_mixin: ^1.2.0
  photo_view: ^0.11.1
  flutter_google_pay: ^0.1.4
  flutter_socket_io: ^0.6.0
  bubble: ^1.2.1
  flutter_countdown_timer: ^4.1.0
  quickblox_sdk: 0.4.3-beta
  another_flushbar: ^1.10.23
  ots:
    git:
      url: git://github.com/fayaz07/ots.git


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.0
  dashed_circle: ^0.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/icons/
    - assets/bottomicons/
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
